services:
  rec_system:
    build: .
    container_name: rec_system
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    name: filmbuddy-network
    external: true
