FROM golang:1.25.3-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /social_service ./src/main.go

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /social_service /app/social_service

COPY internal/config/config.yaml /app/internal/config/config.yaml
COPY internal/migrations /app/internal/migrations

CMD ["/app/social_service"]